### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by ghost**
Updated Buffer() to Buffer.from()

### CODE REVIEW

**Comment by Dekita** [comment]
I dont think the 'new' is required for the Buffer.from() call. :)

**Comment by bowheart** [comment]
Indeed, the `new` keyword isn't required but it looks like it works fine. I must say I'm very confused by it. In my brief testing, both:

```ts
(new Buffer).from('whatever')
```

and

```ts
new (Buffer.from('whatever'))
```

throw errors. I have no idea then how

```ts
new Buffer.from('whatever')
```

works or what it's doing. But it does so...

I'll merge this and publish a new .. minor version? This may be major version territory. But since `Buffer.from` was added in node v5.10.0, I would guess most people using electron are at least at that node version. I think I'll do a minor version, unless there are any objections.

**Comment by Dekita** [comment]
I have it implemented without the 'new' and its also working fine. That's also how node js specifies to use Buffer.from().

**Comment by bowheart** [comment]
Yes, of course. I would never stick the `new` keyword in there either. It doesn't make sense to me that it's possible. I would love for someone to explain to me why `new Buffer.from(...)` works.

The node docs actually do have an example where they (accidentally?) use `new Buffer.from(...)` here: https://nodejs.org/api/buffer.html#buffer_buf_byteoffset

But anyway. It works. It looks like it's meant to work. So I'm not against it - just confused by it.

**Comment by bowheart** [comment]
This has been published in version [2.1.0](https://github.com/bowheart/ejs-electron/releases/tag/v2.1.0)

**Pull request merged**
